TEST_SUBDIR = test_utils
BUILD_DIR = ../../$(TEST_BUILD_ROOT)/$(TEST_SUBDIR)

# We package test_utils as a static library
LIB_NAME = test_utils
OBJS = assert
C_OBJS = assert_helpers

include ../../basedefs.mk
include ../testdefs.mk

include ../testrules.mk
include ../../baserules.mk
