SRC_SUBDIR = utils
SRC_DIR = ../../$(SRC_ROOT)/$(SRC_SUBDIR)
SRC_BUILD_DIR = ../../$(BUILD_ROOT)/$(SRC_SUBDIR)

TEST_BUILD_ROOT_PATH = ../../$(TEST_BUILD_ROOT)
TEST_SUBDIR = utils
BUILD_DIR = $(TEST_BUILD_ROOT_PATH)/$(TEST_SUBDIR)

OBJS = arrays_test strings_test
SRC_OBJS = arrays strings

EXECS = arrays_test strings_test

include ../../basedefs.mk
include ../testdefs.mk

include ../testrules.mk
include ../../baserules.mk
